[package]
name = "instar-lint"
version.workspace = true
edition.workspace = true
description = "Luau source linting"
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
instar-analysis = { path = "../analysis" }
instar-syntax = { path = "../syntax" }
regex.workspace = true
schemars.workspace = true
serde.workspace = true
vermis.workspace = true

[dev-dependencies]
toml.workspace = true

[lints]
workspace = true
