[package]
name = "instar-lint"
version.workspace = true
edition.workspace = true
description = "Luau source linting"
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
glob.workspace = true
regex.workspace = true
schemars.workspace = true
serde.workspace = true

[lints]
workspace = true
