[package]
name = "instar-lint"
version.workspace = true
edition.workspace = true
description = "Luau source linting"
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
glob.workspace = true
instar-check = { path = "../check" }
regex.workspace = true
schemars.workspace = true
serde.workspace = true
vermis = "0.7"

[dev-dependencies]
toml.workspace = true

[lints]
workspace = true
