[package]
name = "instar-format"
version.workspace = true
edition.workspace = true
description = "Luau source formatting"
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
glob.workspace = true
instar-analysis = { path = "../analysis" }
instar-syntax = { path = "../syntax" }
schemars.workspace = true
serde.workspace = true
serde_json.workspace = true
vermis.workspace = true
unicode-width = "0.2"

[dev-dependencies]
toml.workspace = true

[lints]
workspace = true
