[package]
name = "instar-format"
version.workspace = true
edition.workspace = true
description = "Luau source formatting"
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
glob.workspace = true
schemars.workspace = true
serde.workspace = true
vermis = "0.7"

[dev-dependencies]
toml.workspace = true

[lints]
workspace = true
