[package]
name = "instar-bridge"
version.workspace = true
edition.workspace = true
description = "Native Luau bridge"
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
cxx = "1"
instar-analysis = { path = "../analysis" }
serde.workspace = true
serde_json.workspace = true

[build-dependencies]
cmake = "0.1"
cxx-build = "1"
serde_json.workspace = true

[lints]
workspace = true
