[package]
name = "instar-core"
version.workspace = true
edition.workspace = true
description = "Project orchestration for the Luau toolchain"
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
glob.workspace = true
instar-bridge = { path = "../bridge" }
instar-check = { path = "../check" }
instar-format = { path = "../format" }
instar-lint = { path = "../lint" }
schemars.workspace = true
serde.workspace = true
serde_json.workspace = true
toml.workspace = true
vermis = "0.7"

[lints]
workspace = true
